### ISSUE TITLE
Form styles

### ISSUE THREAD

**Issue by galvarez421** [PurdueMarketingAndMedia/purdueTemplates-2015#111]
The template demo website (https://purduemarketingandmedia.github.io/purdueTemplates-2015/builds/production/html/mm/templates/office/office-tiles-4.html and other pages on that site) doesn't appear to demo form design patterns. The Sass/CSS includes some form styles (https://github.com/PurdueMarketingAndMedia/purdueTemplates-2015/blob/ed1f3d83175fbef670c9b52172859b68c30bec81/src/styles/components/mm/elements/_form.scss) but they don't necessarily seem to be used in the HTML (https://github.com/PurdueMarketingAndMedia/purdueTemplates-2015/search?q=purdueForm&unscoped_q=purdueForm). Is it safe to say there are no "official" prescribed form styles associated with the current web templates?

**Comment by jyoung295** [comment]
You're correct, we don't actually have any official branded form styles because whenever we've used forms in the past we have used Qualtrics to build and display them.
