### ISSUE TITLE
Not showing mobile version of hero banner at mobile

### ISSUE THREAD

**Issue by bholaday** [PurdueMarketingAndMedia/purdueTemplates-2015#116]
Is it me or is there a bug for displaying hero banners on the template at mobile? See: https://qa.www.purdue.edu/homecoming/

It doesn’t seem to be displaying the smallest image size but instead loads a larger version.

![Screen Shot 2020-07-15 at 9 57 37 AM](https://user-images.githubusercontent.com/5982996/87554054-a6d0bd00-c681-11ea-9d13-e65532cab89e.png)

**Comment by Yanhuazong** [comment]
The name is a little confusing but the smallest version of the image (Ex-small) is only used for screen size between 768 and 991px where the image has a fixed width of 422px. For screen size smaller than 480px it's using the small image sized 480x350.

**Comment by bholaday** [comment]
I see. Thanks for clarifying.
