### ISSUE TITLE
0 left padding for dropdown link descendants of "first" blackbar links

### ISSUE THREAD

**Issue by galvarez421** [PurdueMarketingAndMedia/purdueTemplates-2015#23]
Due to https://github.com/PurdueMarketingAndMedia/purdueTemplates-2015/blob/master/components/css/global/_nav.scss#L168-L172, if the "first" blackbar link contains a dropdown menu of links, those links will also have 0 left padding. I assume the intention of the 0 left padding is so that the first link in the blackbar is left-aligned with the grid container. But, assuming that the removal of the left padding of the descendant dropdown menu links isn't intentional, would the following Sass make more sense?

`
  .first {
    > a {
      padding-left:0;
    }
  }
`

**Comment by jacobvenable** [comment]
Ah, good point. All of our templated site always have a single "Home" link as the first item in the nav, but we can certainly account for other scenarios. We'll try to get this in the next release.
