### ISSUE TITLE
Awkward touch area for goldbar quicklinks

### ISSUE THREAD

**Issue by bholaday** [PurdueMarketingAndMedia/purdueTemplates-2015#34]
The padding set on the links defines the touch area. In the current version of our templates there is no left padding. Perhaps we could instead put equal padding on all elements and only target the last if we need to modify the distance between it and the search icon.

<img width="1231" alt="screen shot 2018-02-15 at 9 21 33 am" src="https://user-images.githubusercontent.com/5982996/36263902-41c8f390-1239-11e8-8d98-9c9d417cc4aa.png">

**Comment by jobokai** [comment]
Technically couldn't you just add the left padding (and matching right) needed for the search icon instead of the :last quicklink?

**Comment by jobokai** [comment]
That way everything is having equal padding for the touch areas and you don't have to require anything special for the :last one.

**Comment by bholaday** [comment]
Good idea.

**Comment by jacobvenable** [comment]
This will be fixed in the next release with the referenced branch above.
