### ISSUE TITLE
Publish to npm registry

### ISSUE THREAD

**Issue by galvarez421** [PurdueMarketingAndMedia/purdueTemplates-2015#35]
Would it be possible to publish a package containing the templates assets (pretty much everything in the `builds` and `components` folders) to the npm registry?

My team often uses the template assets (Sass files in particular) for our web applications, and it would be useful to be able to depend on the assets from this repo in the same way that we depend on other npm packages. Currently, we add this repo as a dependency in our projects by [including a GitHub URL in our package.json files](https://docs.npmjs.com/files/package.json#github-urls). For example, in one project, I have the following line in package.json:

`"purduetemplates2015": "git+https://github.com/PurdueMarketingAndMedia/purdueTemplates-2015.git#a8eba38"`

This works but I have 2 concerns:
1. Commits by themselves do not follow a documented versioning scheme (like [Semantic Versioning](https://semver.org/)), so trying to take of advantage of updates in the template assets is currently tricky since it's not clear when there are breaking changes from one commit to the next. If the package is on the npm registry, there is [the assumption that Semantic Versioning is being used](https://docs.npmjs.com/getting-started/using-a-package.json#requirements).
2. The Semantic Versioning issue could technically be addressed by creating tags in the repo, but I think the added benefit of publishing the assets to the npm registry is that [unpublishing a package from the npm registry](https://docs.npmjs.com/cli/unpublish) seems at least somewhat harder than [deleting a repo from GitHub](https://help.github.com/articles/deleting-a-repository/) in that you have to jump through an extra hoop to unpublish a package more than a day old. I think this would make consuming the template assets safer.

**Comment by bholaday** [comment]
Hey guys,

This is an interesting idea which we'll need to discuss. @jobokai, do you also depend on assets like this?

Anyone else interested in this?

**Comment by jobokai** [comment]
@bholaday Actually both me and @galvarez421 are on the same team 😄 for student systems. Though we do cover different projects. Right now most of the projects I work on are all custom built solutions (dining.purdue.edu/menus for example). That said we have a large one coming up that will definitely be pulling the templates and packages for usage in our development environments. 

Having the templates on the NPM registry would make it easier to pull specific version releases rather than specific commits. And wouldn't require the need to go in and find the necessary hashes/branch names.

**Comment by bholaday** [comment]
Ah! I'm relatively new and still getting to know everyone in dev world here at Purdue. Again, we'll discuss how we might implement this on our team and definitely appreciate the feedback and suggestions you guys give. Keep 'em coming!

**Comment by jobokai** [comment]
Something else that may be a good idea or at least be a start, [would be tagging commits that represent a version update](https://git-scm.com/book/en/v2/Git-Basics-Tagging). Say for button styles (when it gets merged to master) might be tagged v1.5.7. This would make things more readable when viewing the repo via a GUI tool or command line and being able to specify a stable release you wish to pull. With all of the branches right now it's rather hard to find these version updates.

**Comment by jacobvenable** [comment]
@jobokai We'll start tagging with the next release. It will most likely be v1.6.0.

**Comment by jacobvenable** [comment]
I went ahead and labelled the new release branch as 1.6.0 but also defined it as a pre-release. I'll publish it once we have merged it into the master branch.

**Comment by bholaday** [comment]
We've released the newest version and a small patch already. I'm going to close this issue unless anyone has reason to keep it open. I'll give it a few days.
