### ISSUE TITLE
ReadMe missing development instructions

### ISSUE THREAD

**Issue by jobokai** [PurdueMarketingAndMedia/purdueTemplates-2015#36]
Looking at the readme file it looks like the development section of it is missing on the Master Branch. It would be beneficial for those looking to do a production build or development build to have the appropriate gulp commands.

**Comment by bholaday** [comment]
Good catch. We use these two commands. I'll see if @jacobvenable wants to make any additions/changes.

https://github.com/PurdueMarketingAndMedia/purdueTemplates-2015/commit/8372b1ba809ef25c3653cc9c2c41e5db7c0e2f1f

**Comment by jobokai** [comment]
@bholaday Awesome thanks!
