### ISSUE TITLE
Accessibility focus outline shows when clicking with a mouse on top nav

### ISSUE THREAD

**Issue by bholaday** [PurdueMarketingAndMedia/purdueTemplates-2015#5]

**Comment by bholaday** [comment]
seems to only appear in Safari, Firefox, and Opera

**Comment by jobokai** [comment]
It seems to be an issue with how different browsers treat the :focus pseudo class.
https://stackoverflow.com/questions/26242728/how-can-i-use-focus-when-browsers-behave-differently-chrome-shows-focus-style
https://codepen.io/bfred-it/full/zHqDt

**Comment by jacobvenable** [comment]
At the end of the CodePen page, it mentions possibly using blur() to fix any focus issues. I'll experiment with adding that to the bootstrap JS file. If that doesn't work, we are also considering changing the focus style to a background change. This would still have a visual change for mouse users, but at least it would look less intrusive.
![dropdown-fix](https://user-images.githubusercontent.com/6598084/27153320-fe2254be-511e-11e7-9713-8fed79275ab8.png)

**Comment by drewhallett** [comment]
It looks like Bootstrap styles with :focus get the outline automatically. That's why menu links without bootstrap classes don't have the outline. 

A global *:focus rule applied to the stylesheet would make this consistent between browsers.

Chrome is a different story because it has a user agent style for focus highlighting.

**Comment by jacobvenable** [comment]
I believe each dropdown "opener" uses the class "dropdown-toggle" which is a Bootstrap class. Unfortunately, this class also removes the outline on focus, most likely attempting to avoid the issue we are dealing with now. I started a [pull request](https://github.com/PurdueMarketingAndMedia/purdueTemplates-2015/pull/6) which lists some quick fixes we are making in response to the update. We are going to make the focus styles a bit less intrusive.

We'll continue taking feedback and applying changes next week.

**Comment by bholaday** [comment]
resolved with hotfix: https://github.com/PurdueMarketingAndMedia/purdueTemplates-2015/pull/6
