### ISSUE TITLE
Sidenav Underline Staying on Second Click

### ISSUE THREAD

**Issue by jyoung295** [PurdueMarketingAndMedia/purdueTemplates-2015#62]
When a dropdown link in the side navigation is clicked, a gold underline is added with the `:focus` selector. When the same link is clicked, the menu is removed, but the gold underline persists. This is probably because technically the link is still in the `:focus` state until somewhere else on the page is clicked.

**Example:**
[![https://gyazo.com/27fab142684f2351bcf643c83984f261](https://i.gyazo.com/27fab142684f2351bcf643c83984f261.gif)](https://gyazo.com/27fab142684f2351bcf643c83984f261)

**Comment by jacobvenable** [comment]
I think we're going to need to implement some JS to handle a keyboard vs. mouse click. In the past, I've added a class when the click is caused by a keyboard that will disable the focus styles.

We should make sure to remove that class when the dropdown also loses focus.

**Comment by jyoung295** [comment]
Resolved in #93
