### ISSUE TITLE
Blue border on dropdown menus

### ISSUE THREAD

**Issue by bholaday** [PurdueMarketingAndMedia/purdueTemplates-2015#7]
Posted on behalf of Jennifer Kim:

We use Purdue Web Template v1.5 and blue border appears when side drop down menu is clicked. Previously this happened to the top menus but it was fixed and I just now noticed it’s happening to the side menu

![screen shot 2017-08-16 at 10 06 24 am](https://user-images.githubusercontent.com/5982996/29367345-95dc2ed4-826a-11e7-9aae-9d894d7eae6c.png)

**Comment by jacobvenable** [comment]
Created a [pull request](https://github.com/PurdueMarketingAndMedia/purdueTemplates-2015/pull/16) that contains a fix for this issue.

**Comment by bholaday** [comment]
resolved with https://github.com/PurdueMarketingAndMedia/purdueTemplates-2015/pull/16
