### ISSUE TITLE
.container-fluid and no blackbar acceptable?

### ISSUE THREAD

**Issue by galvarez421** [PurdueMarketingAndMedia/purdueTemplates-2015#70]
My team works primarily on web applications, and we try to use the template as often as it makes sense to do so, but sometimes the default layout seems a bit too constraining for our purposes. Would it be considered acceptable usage of the template to do either of the following?

1) Use Bootstrap .container-fluid class instead of .container class for .goldbar, .top, .footer, and main content area elements
2) Omit the .blackbar component and present global navigation links using a sidebar

The use case is that we would like to be able to essentially use a "dashboard" variation of the default template. The main thing we would like to achieve by using this kind of "dashboad" layout is a more scalable container for global navigation links (i.e., we wouldn't have to worry about navigation links wrapping when there are too many) and providing more area for the main content, especially to accommodate somewhat complex tables. As you can see in the images below, using .container-fluid for just the main content element but not the global template components leads to unaligned grids.

![container-fluid](https://user-images.githubusercontent.com/12755056/42457118-90ed1a18-8364-11e8-817a-f837f9758115.png)

![container](https://user-images.githubusercontent.com/12755056/42457127-95f9d898-8364-11e8-8919-e7713df06d17.png)

**Comment by jacobvenable** [comment]
My initial reaction says that it could possibly look sketchy since it's attempting to mimic the Purdue templates, but I definitely see what you mean in the 2nd screen shot. We'll talk with the design/brand team and I'll let you know.

**Comment by galvarez421** [comment]
Cool, thank you! For what it's worth, the web app that we are currently hoping to use this layout for requires authentication with a valid Purdue career account so the layout would not be viewable by the public; I think there might be a few public non-authenticated pages but we could use a different layout for those pages if necessary.

**Comment by jacobvenable** [comment]
I think that would definitely help with encouraging confidence that it's legitimate. I'll make sure they're aware!

**Comment by jacobvenable** [comment]
After talking with the team, we're in agreement that it best that when using the templates, to follow them as closely as possible; however, we also understand that the templates won't necessarily fit for all use-cases.

In this situation, we're thinking it should be alright to use the layout in your 1st screenshot on the application that sits behind authentication. As for any public-facing pages, go ahead and use the template's original layout. Would that work for your team?

**Comment by galvarez421** [comment]
Yes, that would work great. Thanks for the prompt replies!
