### ISSUE TITLE
Footer Tagline SVG display issue

### ISSUE THREAD

**Issue by jobokai** [PurdueMarketingAndMedia/purdueTemplates-2015#71]
I'm not sure if this is an intentional change or just a bug. I thought the WE ARE PURDUE line spanned the full width similar to the WHAT WE MAKE line. Screenshot below:

![image](https://user-images.githubusercontent.com/13200689/42460217-5142093a-836b-11e8-9822-dd8d31f7325a.png)

If it's intentional feel free to close this issue.

**Comment by jacobvenable** [comment]
@jobokai Yep, this was an intentional design change! Thanks for checking though :)

**Comment by jobokai** [comment]
Do you have an SVG file download anywhere for use?
