### ISSUE TITLE
Update version in package.json

### ISSUE THREAD

**Issue by galvarez421** [PurdueMarketingAndMedia/purdueTemplates-2015#77]
Can you please update the version number in package.json to be in sync with the tags/releases? This will enable proper versioning in package managers like npm and Yarn. Otherwise, if the version number is let unchanged, the package managers will be unaware of changes.

**Comment by galvarez421** [comment]
Nevermind! The package.json version number only matters if you are installing from the npm registry. Yarn and npm allow for installing using a Git remote URL with a tag specified.

Updating the package.json version number would be relevant only if this package was published to the npm registry (see #35)

**Comment by jacobvenable** [comment]
Because of #35, I'll go ahead and update this in the next maintenance branch since it makes sense for the versions to match anyways. Thanks!
