### ISSUE TITLE
On Master branch, error message 'This page is calling an old version of the custom search api', master should be updated to fix this.

### ISSUE THREAD

**Issue by jobokai** [PurdueMarketingAndMedia/purdueTemplates-2015#8]
Working on a web app today and I pulled master down for template use and I'm noticing that the error message for the old version of the Custom Search API is still around. I know there was a fix somewhere, but evidently it's not on master. Could we get that updated?

**Comment by jacobvenable** [comment]
@jobokai Thank you for bringing this to our attention. I updated this within our CMS, but failed to also do so in this repo. We'll make sure this will be fixed in the next update.

**Comment by jacobvenable** [comment]
Created a [pull request](https://github.com/PurdueMarketingAndMedia/purdueTemplates-2015/pull/16) that contains a fix for this issue.

**Comment by bholaday** [comment]
resolved with https://github.com/PurdueMarketingAndMedia/purdueTemplates-2015/pull/16
