### ISSUE TITLE
Quote and blockquote bar/border styling not scalable

### ISSUE THREAD

**Issue by galvarez421** [PurdueMarketingAndMedia/purdueTemplates-2015#82]
The left bar/border used for quote and blockquote elements does not seem to scale well for larg(er) amounts of text. I think is due to the percentage-based styles, specifically https://github.com/PurdueMarketingAndMedia/purdueTemplates-2015/blob/v1.6.7/components/css/partials/_quote.scss#L63 and https://github.com/PurdueMarketingAndMedia/purdueTemplates-2015/blob/v1.6.7/components/css/partials/_quote.scss#L65.

Example from https://www.purdue.edu/brand/elements/web/pattern-library/typography.php:

![1](https://user-images.githubusercontent.com/12755056/51704807-f7fd7480-1fe7-11e9-849d-8f3248318061.png)

Example from https://www.purdue.edu/brand/elements/web/pattern-library/typography.php with much more text:

![2](https://user-images.githubusercontent.com/12755056/51704813-fd5abf00-1fe7-11e9-991b-10778b99195f.png)

I think it would make sense to make the styling more scalable given that blockquotes could justifiably be rather long in some cases.

**Comment by jacobvenable** [comment]
This was added to development, but we'll be implementing it in a hotfix as well. Thanks for bringing it to our attention!

**Comment by jacobvenable** [comment]
Issue addressed and merged in #84
