### ISSUE TITLE
Invalid alt attributes on social media footer links

### ISSUE THREAD

**Issue by galvarez421** [PurdueMarketingAndMedia/purdueTemplates-2015#9]
https://github.com/PurdueMarketingAndMedia/purdueTemplates-2015/blob/71b2c8a30271b0e5f0e988c18f77501acf27be33/components/html/modules/footer/_resources.html#L73-L79 shows that alt attributes are being used for the social media links. This seems to be invalid HTML: alt attribute is supported only for certain elements, not including the anchor element (https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes). I recommend using title attribute instead of alt attribute for these anchor elements.

**Comment by jacobvenable** [comment]
You are correct. These have been lingering for quite some time but we'll get them corrected.

**Comment by jacobvenable** [comment]
Created a [pull request](https://github.com/PurdueMarketingAndMedia/purdueTemplates-2015/pull/16) that contains a fix for this issue.

**Comment by bholaday** [comment]
resolved with https://github.com/PurdueMarketingAndMedia/purdueTemplates-2015/pull/16
